version: 7
profiles:
  - type: local
    name: User default
    options:
      command: /bin/bash
      args:
        - '--login'
      env: {}
    isBuiltin: false
    isTemplate: false
    id: local:custom:User-default:07a969f0-8605-4fc7-a1f0-f33906260a4a
hotkeys:
  toggle-window: []
  copy-current-path: []
  scroll-to-bottom: []
  ctrl-c:
    - Ctrl-C
  copy: []
  paste: []
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in: []
  zoom-out: []
  reset-zoom: []
  home:
    - - Shift-Left
  end:
    - - Shift-Right
  previous-word: []
  next-word: []
  delete-previous-word: []
  delete-next-word: []
  search:
    - - Ctrl-F
  pane-focus-all: []
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings: []
  serial: []
  restart-serial-session: []
  new-window: []
  new-tab:
    - - Ctrl-T
  profile: {}
  profile-selectors: {}
  toggle-fullscreen: []
  close-tab:
    - - Alt-T
  reopen-tab: []
  toggle-last-tab: []
  rename-tab: []
  next-tab: []
  previous-tab: []
  move-tab-left: []
  move-tab-right: []
  rearrange-panes: []
  duplicate-tab: []
  tab-1:
    - - Ctrl-1
  tab-2:
    - - Ctrl-2
  tab-3:
    - - Ctrl-3
  tab-4:
    - - Ctrl-4
  tab-5:
    - - Ctrl-5
  tab-6:
    - - Ctrl-6
  tab-7:
    - - Ctrl-7
  tab-8:
    - - Ctrl-8
  tab-9:
    - - Ctrl-9
  tab-10: []
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - - Ctrl-Shift-Right
  split-bottom:
    - - Ctrl-Shift-Down
  split-left: []
  split-top: []
  pane-nav-right:
    - - Ctrl-Right
  pane-nav-down:
    - - Ctrl-Down
  pane-nav-up:
    - - Ctrl-Up
  pane-nav-left:
    - - Ctrl-Left
  pane-nav-previous: []
  pane-nav-next: []
  pane-maximize: []
  close-pane:
    - - Alt-P
  switch-profile: []
  profile-selector: []
  delete-line:
    - Ctrl-Shift-Backspace
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-page-up:
    - Alt-PageUp
  scroll-up:
    - Ctrl-Shift-Up
  scroll-down:
    - Ctrl-Shift-Down
  scroll-page-down:
    - Alt-PageDown
  settings-tab: {}
  group-selectors: {}
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  command-selector:
    - Ctrl-Shift-P
terminal:
  searchOptions: {}
  colorScheme:
    name: SeaShells
    foreground: '#deb88d'
    background: '#09141b'
    cursor: '#fca02f'
    colors:
      - '#17384c'
      - '#d15123'
      - '#027c9b'
      - '#fca02f'
      - '#1e4950'
      - '#68d4f1'
      - '#50a3b5'
      - '#deb88d'
      - '#434b53'
      - '#d48678'
      - '#628d98'
      - '#fdd39f'
      - '#1bbcdd'
      - '#bbe3ee'
      - '#87acb4'
      - '#fee4ce'
  font: Roboto Regular
  customColorSchemes:
    - name: ayu
      foreground: '#e6e1cf'
      background: '#0f1419'
      cursor: '#f29718'
      colors:
        - '#000000'
        - '#ff3333'
        - '#b8cc52'
        - '#e7c547'
        - '#36a3d9'
        - '#f07178'
        - '#95e6cb'
        - '#ffffff'
        - '#323232'
        - '#ff6565'
        - '#eafe84'
        - '#fff779'
        - '#68d5ff'
        - '#ffa3aa'
        - '#c7fffd'
        - '#ffffff'
    - name: ayu_light
      foreground: '#5c6773'
      background: '#fafafa'
      cursor: '#ff6a00'
      colors:
        - '#000000'
        - '#ff3333'
        - '#86b300'
        - '#f29718'
        - '#41a6d9'
        - '#f07178'
        - '#4dbf99'
        - '#ffffff'
        - '#323232'
        - '#ff6565'
        - '#b8e532'
        - '#ffc94a'
        - '#73d8ff'
        - '#ffa3aa'
        - '#7ff1cb'
        - '#ffffff'
  scrollbackLines: 30000
  bell: audible
  background: colorScheme
  cursorBlink: false
  lightColorScheme:
    name: ayu_light
    foreground: '#5c6773'
    background: '#fafafa'
    cursor: '#ff6a00'
    colors:
      - '#000000'
      - '#ff3333'
      - '#86b300'
      - '#f29718'
      - '#41a6d9'
      - '#f07178'
      - '#4dbf99'
      - '#ffffff'
      - '#323232'
      - '#ff6565'
      - '#b8e532'
      - '#ffc94a'
      - '#73d8ff'
      - '#ffa3aa'
      - '#7ff1cb'
      - '#ffffff'
  fontSize: 16
ssh: {}
configSync:
  parts: {}
clickableLinks:
  modifier: ctrlKey
appearance:
  frame: full
  tabsLocation: right
hacks: {}
enableWelcomeTab: false
pluginBlacklist:
  - save-output
profileDefaults: {}
electronFlags:
  - - force_discrete_gpu
    - '0'
enableAnalytics: false
recoverTabs: false
groups: []
accessibility: {}
providerBlacklist: []
commandBlacklist: []
profileBlacklist: []
